name: Frontend Pipeline

on:
  push:
    branches:
      - main

jobs:
  frontend:
      runs-on: ubuntu-latest
      env:
        working-dir: ./frontend
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - name: Build Project
          working-directory: ${{env.working-dir}}
          run: |
            npm install
            npm run build --if present
            npm test
#        - name: Deploy
#          uses: appleboy/scp-action@master
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.SSHUSERNAME }}
#            password: ${{ secrets.SSHPASSWORD }}
#            source: 'frontend/out/*'
#            target: ${{ secrets.FRONTEND_DESTINATION }}
#            strip_components: 2
#            rm: true