name: Release Artifcat

on:
  release:
   type: [published]

jobs:
  create-release-artifact:
    runs-on: ubuntu-latest
    steps:
     - name: Setup Python
       uses: actions/setup-python@v2.2.2
     - name: Install dependencies
       run: |
           python -m pip install --upgrade pip
           pip install flake8
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           pip install -e.
     - run: |
         touch test.txt
     - name: Upload package
       uses: actions/upload-artifact@v2
       with:
         name: dev-package
         path: test.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: run linter [flake8]
        run: flake8.
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests [pytest]
        run: pytest

  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: create build artifact [sdist]
        run: python setup.py sdist
      - name: get release name
        id: get_release_name
        run: echho ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: limbus-${{ steps.get_release_name.outputs.VERSION }}
          path: dist/*