name: Validation Pipeline

on:
  push:
    branches:
      - feature/**
      - fix/**

jobs:
#  super.lint:
#    name: Lint code base
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Run Production Stage Pipeline
#        uses: github/super-linter@v3
#        env:
#          DEFAULT_BRANCH:
#            feature/**,
#            fix/**
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Setup Python
       uses: actions/setup-python@v2.2.2
     - name: Install dependencies
       run: |
           npm install
           npm run build
#           python -m pip install --upgrade pip
#           pip install flake8
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#           pip install -e.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: run linter [flake8]
        run: flake8.
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests [pytest]
        run: pytest
